Repository kubernetes-sigs/karpenter, pull requests merged in 2023-12, with the labels that each got.

#833 ci: use kube-apiserver v1.25.16 for k8s 1.25 CI
  hack/toolchain.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#836 ci: update issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#840 chore: remove the remainder of the alpha references
  pkg/apis/v1alpha5/labels.go
  pkg/apis/v1alpha5/limits.go
  pkg/apis/v1alpha5/machine.go
  pkg/apis/v1alpha5/machine_status.go
  pkg/apis/v1alpha5/provisioner.go
  pkg/apis/v1alpha5/provisioner_defaults.go
  pkg/apis/v1alpha5/provisioner_status.go
  pkg/apis/v1alpha5/provisioner_validation.go
  pkg/apis/v1alpha5/register.go
  pkg/apis/v1alpha5/suite_test.go
  pkg/apis/v1alpha5/zz_generated.deepcopy.go
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodeclaim_validation.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/cloudprovider/fake/instancetype.go
  pkg/cloudprovider/metrics/cloudprovider_test.go
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/metrics/node/controller.go
  pkg/controllers/metrics/nodepool/controller.go
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/terminator/terminator.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/emptiness.go
  pkg/controllers/nodeclaim/disruption/expiration.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/launch_test.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodepool/counter/controller.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/informer/nodeclaim.go
  pkg/controllers/state/statenode.go
  pkg/controllers/state/suite_test.go
  pkg/controllers/state/zz_generated.deepcopy.go
  pkg/metrics/constants.go
  pkg/metrics/metrics.go
  pkg/operator/controller/suite_test.go
  pkg/scheduling/requirements.go
  pkg/test/machine.go
  pkg/test/nodeclaim.go
  pkg/test/nodes.go
  pkg/test/provisioner.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/nodepool/nodepool.go
  pkg/utils/nodepool/suite_test.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#839 Revert "chore: Revert staging changes for budgets (#799)"
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#842 ci: Auto-update composite actions with scripting
  .github/dependabot.yaml
  Makefile
  hack/dependabot.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#783 fix: correctly handle non-existent / empty StorageClasses
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/controllers/provisioning/suite_test.go
  pkg/scheduling/volumeusage.go
  pkg/test/storage.go
  pkg/utils/volume/volume.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#847 chore: update license notice for volume util
  pkg/utils/volume/volume.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#846 chore: add webhook validation for budgets
  pkg/apis/v1beta1/nodepool_validation.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#850 chore: change naming of budget.crontab and budget.maxUnavailable
  designs/disruption-controls.md
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
  pkg/apis/v1beta1/nodepool_validation.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#851 chore: Move the `karpenter_build_info` metric to karpenter
  pkg/operator/operator.go
  pkg/operator/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#856 chore: Add goarch label to karpenter_build_info Prometheus metric
  pkg/operator/operator.go
  pkg/operator/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#861 ci: Enable codeql for github actions
  .github/workflows/codeql-analysis.yaml
  .github/workflows/stale.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#860 chore: Fix consistent ordering of NodePools and Provisioners
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, size/L

#862 chore: Drop events for consolidation disabled when we have a different policy
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#849 feat: Disruption Budgets
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/expiration_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
  pkg/test/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#864 fix: remove event filter for nodepool hash controller
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodepool/hash/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#865 chore: remove nodeclaim disruption controller node watcher
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/expiration.go
  pkg/controllers/nodeclaim/disruption/expiration_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#866 fix: don't panic on shutdown for nil nodepools for logging budgets
  pkg/controllers/disruption/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#867 docs: Add `RELEASE.md` documentation
  RELEASE.md
Labels: cncf-cla: yes, lgtm, approved, size/M

#875 chore: Fix `karpenter_nodeclaims_drifted` metric
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/emptiness_test.go
  pkg/controllers/nodeclaim/disruption/expiration_test.go
  pkg/utils/nodeclaim/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#869 feat: Initialize the VEX feed
  .openvex/templates/README.md
  .openvex/templates/main.openvex.json
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/M

#884 ci(workflows): least privileged token permissions
  .github/workflows/codeql-analysis.yaml
  .github/workflows/presubmit.yaml
  .github/workflows/release.yaml
  .github/workflows/stale.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#878 docs: SECURITY-INSIGHTS.yml Configuration
  SECURITY-INSIGHTS.yml
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#881 fix: Fix `karpenter_nodeclaims_drifted` metric for `v0.33.x`
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/emptiness_test.go
  pkg/controllers/nodeclaim/disruption/expiration_test.go
  pkg/utils/nodeclaim/nodeclaim.go
Labels: cncf-cla: yes, approved, size/M

#883 chore: Fix consistent ordering of NodePools and Provisioners (#860) into `HEAD`
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#882 chore: Fix consistent ordering of NodePools and Provisioners (#860) for `v0.33.x`
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#885 docs: Update meeting link to Community Owned Zoom
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#888 fix: typo in 'SECURITY-INSIGHTS.YML' file
  SECURITY-INSIGHTS.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#901 chore: Release leader election in manager config
  pkg/operator/operator.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#898 chore(deps): bump k8s deps
  go.mod
  go.sum
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/test/pods.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#907 Cleanup Unnecessary Nodepool/Nodeclaim util functions and inline them
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/emptiness.go
  pkg/controllers/nodeclaim/disruption/expiration.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/liveness.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodepool/counter/controller.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/provisioning/provisioner.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/nodepool/nodepool.go
  pkg/utils/nodepool/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/L

#889 Ensure SLSA Attestations are Generated when Possible
  .github/workflows/release.yaml
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/S

#914 ci: Fix tejolote release attestation step
  .github/workflows/release.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#870 ci: Added GitHub action to generate OpenVEX data with each release
  .github/workflows/release.yaml
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/S

#900 Dependencies Policy
  SECURITY-INSIGHTS.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#917 feat: add metric for disruption budgets
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/expiration_test.go
  pkg/controllers/disruption/metrics.go
Labels: cncf-cla: yes, lgtm, approved, size/L
