Repository kubernetes-sigs/karpenter, pull requests merged in 2023-11, with the labels that each got.

#815 remove gfcroft from list of 3rd parties yet to sign CNCF CLA - he has now signed
  NOTICE
Labels: lgtm, approved

#816 chore: Update owner alias for ellistarn
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#812 chore: Drop NodePool Owner Key from codebase
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/types.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodepool/counter/controller.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/statenode.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/nodepool/nodepool.go
Labels: cncf-cla: yes, approved, size/L

#819 chore: Remove remaining alpha fields from codebase
  pkg/apis/apis.go
  pkg/apis/crds/karpenter.sh_machines.yaml
  pkg/apis/crds/karpenter.sh_provisioners.yaml
  pkg/apis/v1alpha5/doc.go
  pkg/apis/v1alpha5/provisioner.go
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/metrics/node/suite_test.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/metrics.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/events.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/statenode.go
  pkg/controllers/state/suite_test.go
  pkg/metrics/metrics.go
  pkg/operator/operator.go
  pkg/scheduling/requirement.go
  pkg/test/environment.go
  pkg/test/expectations/expectations.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodepool/nodepool.go
  pkg/utils/nodepool/suite_test.go
  pkg/utils/provisioner/provisioner.go
  pkg/utils/provisioner/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#820 chore: Add back approvers with `kubernetes-sigs` membership
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#821 [DRAFT] BREAKING CHANGE: Update options defaults for v1beta1
  pkg/apis/apis.go
  pkg/apis/settings/injectable.go
  pkg/apis/settings/settings.go
  pkg/apis/settings/suite_test.go
  pkg/apis/settings/zz_generated.deepcopy.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/operator/injection/fake/settings.go
  pkg/operator/injection/injection.go
  pkg/operator/injection/suite_test.go
  pkg/operator/logging/logging.go
  pkg/operator/operator.go
  pkg/operator/options/injectable.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/settings.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#826 chore: Rename controllers constructors to `NewController`
  pkg/controllers/controllers.go
  pkg/controllers/leasegarbagecollection/controller.go
  pkg/controllers/nodeclaim/consistency/controller.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/controllers/nodepool/counter/controller.go
  pkg/controllers/nodepool/counter/suite_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#828 chore: Fix configmap waiter for `karpenter-global-settings`
  pkg/operator/injection/injection.go
  pkg/operator/injection/suite_test.go
  pkg/operator/logging/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L

#830 chore: Drop `setFlags` from options parsing
  pkg/operator/options/options.go
Labels: cncf-cla: yes, lgtm, approved, size/S
