Repository kubernetes-sigs/karpenter, pull requests merged in 2024-07, with the labels that each got.

#1377 chore: Add disruption by reason to the v1 NodePool API
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_budgets_test.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1380 chore: update kwok to v0.5.2 and scale back replicas
  hack/install-kwok.sh
  kwok/cloudprovider/cloudprovider.go
  kwok/cloudprovider/const.go
  kwok/cloudprovider/instance_types.json
Labels: cncf-cla: yes, lgtm, approved, size/L

#1375 chore: Group consolidation warning log lines together
  pkg/controllers/provisioning/provisioner.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1382 chore: Remove usage of `knative.dev` logger
  pkg/apis/v1/suite_test.go
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/utils/disruption/disruption.go
  pkg/utils/node/suite_test.go
  pkg/utils/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1383 chore: Move native sidecar container testing out of DaemonSet Context
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1386 chore: address GO-2024-2963
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1387 chore: remove knative ptr
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1365 feat: Adding print columns for v1 NodePool
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodepool.go
  pkg/controllers/nodepool/counter/controller.go
  pkg/controllers/nodepool/counter/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1336 feat: require and then remove karpenter startup taint
  Makefile
  go.mod
  go.sum
  pkg/apis/v1beta1/taints.go
  pkg/cloudprovider/types.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/initialization_test.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/test/expectations/expectations.go
  pkg/test/nodes.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/M

#1385 chore: Add status conditions to nodepool and nodeclaim
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim_status.go
  pkg/apis/v1/nodepool_status.go
  pkg/apis/v1/zz_generated.deepcopy.go
  pkg/apis/v1beta1/nodeclaim_status.go
  pkg/apis/v1beta1/nodepool_status.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/controllers.go
  pkg/controllers/nodeclaim/consistency/controller.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
  pkg/controllers/nodepool/validation/controller.go
  pkg/controllers/nodepool/validation/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/test/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, needs-ok-to-test

#1248 chore: Add status conditions on nodepool
  kwok/cloudprovider/cloudprovider.go
  pkg/apis/v1/nodeclaim_conversion_test.go
  pkg/apis/v1/nodepool_conversion_test.go
  pkg/apis/v1/nodepool_status.go
  pkg/apis/v1/suite_test.go
  pkg/apis/v1beta1/nodepool_status.go
  pkg/apis/v1beta1/suite_test.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/leasegarbagecollection/suite_test.go
  pkg/controllers/metrics/node/suite_test.go
  pkg/controllers/metrics/nodepool/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/controllers/nodepool/counter/suite_test.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/nodepool/readiness/controller.go
  pkg/controllers/nodepool/readiness/suite_test.go
  pkg/controllers/nodepool/validation/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/suite_test.go
  pkg/operator/operator.go
  pkg/test/expectations/expectations.go
  pkg/test/nodeclass.go
  pkg/test/nodepool.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  pkg/test/v1alpha1/doc.go
  pkg/test/v1alpha1/testnodeclass.go
  pkg/test/v1alpha1/testnodeclass_status.go
  pkg/test/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/node/suite_test.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/nodepool/nodepool.go
  pkg/utils/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, needs-ok-to-test

#1393 chore: Add Kubelet Annotation for the Conversion webhooks
  pkg/apis/v1/labels.go
  pkg/apis/v1/nodeclaim_conversion.go
  pkg/apis/v1/nodeclaim_conversion_test.go
  pkg/apis/v1/nodepool_conversion.go
  pkg/apis/v1/nodepool_conversion_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1394 chore: fix kwok for previous changes
  hack/install-kwok.sh
  kwok/charts/templates/clusterrole.yaml
  kwok/cloudprovider/cloudprovider.go
  pkg/controllers/nodepool/validation/controller.go
  pkg/controllers/nodepool/validation/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1395 test: fix e2e tests assertion
  test/suites/perf/scheduling_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1398 chore: Deprecate functional library in favor of lo and operatorpkg
  go.mod
  go.sum
  kwok/apis/apis.go
  pkg/apis/apis.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/controllers/provisioning/scheduling/topologynodefilter.go
  pkg/scheduling/requirements.go
  pkg/test/environment.go
  pkg/test/v1alpha1/testnodeclass.go
  pkg/utils/atomic/lazy.go
  pkg/utils/functional/functional.go
  pkg/utils/functional/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1399 test: fix kind cluster test cleanup flakes
  hack/install-kwok.sh
  test/pkg/environment/common/setup.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1401 chore: update nodepool readiness to rely on nodeClass deletion timestamp
  pkg/controllers/nodepool/readiness/controller.go
  pkg/controllers/nodepool/readiness/suite_test.go
  pkg/controllers/provisioning/provisioner.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1374 chore: show caller in debug LogLevel
  pkg/operator/logging/logging.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1388 chore: Add operator status condition metrics
  kwok/main.go
  pkg/controllers/controllers.go
  pkg/operator/operator.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1404 chore: Add check for conflict during registration flow
  pkg/controllers/nodeclaim/lifecycle/registration.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1403 chore: drop validation webhooks and disable webhook flag
  go.mod
  go.sum
  pkg/apis/v1/nodeclaim_validation.go
  pkg/apis/v1/nodeclaim_validation_cel_test.go
  pkg/apis/v1/nodeclaim_validation_webhook_test.go
  pkg/apis/v1/nodepool_validation.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/nodepool_validation_webhook_test.go
  pkg/apis/v1beta1/nodeclaim_validation.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
  pkg/apis/v1beta1/nodeclaim_validation_webhook_test.go
  pkg/apis/v1beta1/nodepool_validation.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1331 chore: Validate do not disrupt annotation on node is true
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/S

#1408 fix: update nodeClassRef.apiVersion refs to group
  pkg/operator/operator.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodepool/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1409 test: upgrade tests and change to preferred pod affinity
  pkg/test/pods.go
  test/suites/perf/scheduling_test.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1410 chore: Removed deadcode
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/events/events.go
  pkg/test/expectations/expectations.go
  pkg/utils/atomic/cachedvar.go
  pkg/utils/atomic/lazy.go
  pkg/utils/atomic/suite_test.go
  pkg/utils/env/env.go
  pkg/utils/pretty/changemonitor.go
  pkg/utils/resources/resources.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1411 test: add kind kwok e2es to presubmit
  .github/workflows/kind-e2e.yaml
  test/suites/perf/scheduling_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1415 chore: fix kwok permissions
  kwok/charts/templates/clusterrole.yaml
  kwok/charts/templates/role.yaml
  test/suites/perf/scheduling_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#916 feat: disruption.terminationGracePeriod
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/labels.go
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/zz_generated.deepcopy.go
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/events/events.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/node/termination/terminator/terminator.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/utils/pod/scheduling.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/XXL

#1416 test: add cluster log dump when test fails
  test/pkg/environment/common/setup.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1417 chore: capitalize disruption budgets by reason
  designs/disruption-controls-by-reason.md
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1412 chore: Remove v1beta1 kubelet compatibility NodePool Annotation hash from v1 NodePool
  pkg/apis/v1/nodepool.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1424 chore: pretty print cluster on testing
  test/pkg/environment/common/setup.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1432 chore: Only Include the kubelet annotation when present in v1beta1
  pkg/apis/apis.go
  pkg/apis/v1/labels.go
  pkg/apis/v1/nodeclaim_conversion.go
  pkg/apis/v1/nodeclaim_conversion_test.go
  pkg/apis/v1/nodepool_conversion.go
  pkg/apis/v1/nodepool_conversion_test.go
  pkg/apis/v1beta1/labels.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1426 chore: move expireAfter to NodeClaimTemplate
  Makefile
  hack/kwok/conversion.sh
  hack/kwok/requirements.sh
  hack/mutation/nodepool.sh
  hack/toolchain.sh
  kwok/charts/README.md
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  kwok/charts/templates/deployment.yaml
  kwok/charts/templates/secret-webhook-cert.yaml
  kwok/charts/templates/service.yaml
  kwok/charts/values.yaml
  kwok/main.go
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodeclaim_conversion.go
  pkg/apis/v1/nodeclaim_conversion_test.go
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_conversion.go
  pkg/apis/v1/nodepool_conversion_test.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/zz_generated.deepcopy.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/expiration/controller.go
  pkg/controllers/nodeclaim/expiration/suite_test.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/operator/injection/injection.go
  pkg/operator/operator.go
  pkg/test/environment.go
  pkg/utils/disruption/disruption.go
  pkg/webhooks/webhooks.go
  test/pkg/environment/common/environment.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L, needs-rebase

#1427 test: implement nodeclaim.spec.terminationGracePeriod CEL tests
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodeclaim_validation_cel_test.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1441 chore: add permissions for tgp
  kwok/charts/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1435 test: Improved Disruption Test Suite duration from 527 seconds to 38 seconds
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1436 ci: Updated Karpenter Evaluate version for e2e tests action
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1431 chore: Reconfigure metrics that are duplicated
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/orchestration/metrics.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/metrics/nodepool/controller.go
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/expiration/suite_test.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1439 fix: put webhook disable option back
  kwok/charts/README.md
  kwok/charts/templates/deployment.yaml
  kwok/charts/templates/role.yaml
  kwok/charts/templates/secret-webhook-cert.yaml
  kwok/charts/templates/service.yaml
  kwok/charts/values.yaml
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1459 chore: Update counter metrics to have suffix _total
  pkg/controllers/leasegarbagecollection/metrics.go
  pkg/controllers/leasegarbagecollection/suite_test.go
  pkg/controllers/nodeclaim/consistency/metrics.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/emptiness_test.go
  pkg/controllers/nodeclaim/expiration/suite_test.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1460 chore: remove readiness check on cache sync
  pkg/operator/operator.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1465 test: remove kind due to flakes
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1467 chore: reconfigure pod startup metric
  pkg/controllers/metrics/pod/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1458 chore: drop metrics in favour of workqueue metrics
  pkg/controllers/disruption/orchestration/metrics.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/metrics.go
  pkg/metrics/metrics.go
  pkg/metrics/workqueue_provider.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1462 feat: change metrics port
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test, needs-rebase

#1472 feat: Remove karpenter.sh/managed-by var
  pkg/apis/v1/labels.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1468 chore: rename disruption taint
  pkg/apis/v1/taints.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/provisioning/controller.go
  pkg/controllers/state/statenode.go
  pkg/utils/pod/scheduling.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1473 docs: Change example NodePool in kwok readme from v1beta to v1.
  kwok/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1222 [RFC] Karpenter v1 API & Roadmap Proposal
  designs/v1-api.md
  designs/v1-roadmap.md
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1477 chore: Add logging config dropping to the v1 RFC
  designs/v1-roadmap.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#1461 chore: add script for install kube-prometheus.
  .github/actions/install-prometheus/action.yaml
  hack/install-prometheus.sh
Labels: kind/cleanup, cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1481 chore: remove tgp from v1beta1
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1453 feat: implement consolidateAfter
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim_status.go
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_conversion.go
  pkg/apis/v1/nodepool_conversion_test.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/zz_generated.deepcopy.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/validation.go
  pkg/controllers/nodeclaim/disruption/consolidation.go
  pkg/controllers/nodeclaim/disruption/consolidation_test.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/emptiness.go
  pkg/controllers/nodeclaim/disruption/emptiness_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/podevents/controller.go
  pkg/controllers/nodeclaim/podevents/suite_test.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/metrics/constants.go
  pkg/utils/node/node.go
  pkg/utils/pod/scheduling.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1469 feat: Drop Support for Log Config, Add Log Paths
  pkg/operator/logging/logging.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1484 chore: Bump operatorpkg with latest metrics
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1482 chore: Add v1 APIs for v0.33.x
  Makefile
  go.mod
  go.sum
  hack/mutation/nodepool.sh
  hack/toolchain.sh
  hack/validation/kubelet.sh
  hack/validation/labels.sh
  hack/validation/requirements.sh
  hack/validation/taint.sh
  pkg/apis/apis.go
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/doc.go
  pkg/apis/v1/duration.go
  pkg/apis/v1/labels.go
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodeclaim_defaults.go
  pkg/apis/v1/nodeclaim_status.go
  pkg/apis/v1/nodeclaim_validation.go
  pkg/apis/v1/nodeclaim_validation_cel_test.go
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_budgets_test.go
  pkg/apis/v1/nodepool_defaults.go
  pkg/apis/v1/nodepool_status.go
  pkg/apis/v1/nodepool_validation.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/register.go
  pkg/apis/v1/suite_test.go
  pkg/apis/v1/taints.go
  pkg/apis/v1/zz_generated.deepcopy.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/test/pods.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1489 chore: Status validation to be on v1beta1 NodeClaims
  hack/validation/status.sh
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#1490 fix: Bump `github.com/awslabs/operatorpkg` to fix race condition
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1496 chore: Add status validation to v1
  hack/validation/status.sh
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S
