Repository kubernetes-sigs/karpenter, pull requests merged in 2024-03, with the labels that each got.

#1057 chore: Cleanup unused code bits in scheduling
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/scheduling/storageclass.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1059 docs: Update documented stability level for spot-to-spot consolidation
  Makefile
  hack/toolchain.sh
  kwok/charts/Chart.yaml
  kwok/charts/README.md
  kwok/charts/README.md.gotmpl
  kwok/charts/values.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#1063 fix: add hardcoded utc prefix to crontab
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1064 chore: cherry pick commit (#1063)
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1068 cherrypick: fix: add hardcoded utc prefix to crontab (#1063)
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1065 chore: Reason only in terms of NodePools in the scheduler
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1070 fix: Changing the MaxInstanceTypes back to original value of 60 in order to…
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1074 cherrypick: fix: Changing the MaxInstanceTypes back to original value of 60 in order to reduce the request size to be sent to launch APIs.order t
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1015 RFC: Propose Drift Hash Versioning
  designs/drift-hash-versioning.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#1073 fix: Add capacity-type label to karpenter_nodes_created and karpenter_node…
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/liveness.go
  pkg/controllers/provisioning/provisioner.go
  pkg/metrics/constants.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1077 fix: add shebang line in install-kwok.sh to execute commands with bash
  hack/install-kwok.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1075 fix: fix spurious logging for non-CSI volumes
  pkg/scheduling/volumeusage.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1016 feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1018 feat: Drop the hostname requirement when handling PV topology
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/controllers/provisioning/suite_test.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1091 ci: add go version to dep cache key
  .github/actions/install-deps/action.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1082 feat: Drop the hostname requirement when handling PV topology for release-v0.33.x (#1018)
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/controllers/provisioning/suite_test.go
  pkg/test/statefulsets.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1083 feat: Drop the hostname requirement when handling PV topology for release-v0.34.x (#1018)
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/controllers/provisioning/suite_test.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1084 feat: Drop the hostname requirement when handling PV topology for release-v0.35.x (#1018)
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/controllers/provisioning/suite_test.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1086 chore: Use strategic merge patching for Core APIs
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/terminator/terminator.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1081 feat: Drop the hostname requirement when handling PV topology for release-v0.32.x (#1018)
  hack/toolchain.sh
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/nodepool_test.go
  pkg/controllers/provisioning/provisioner_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
  pkg/test/statefulsets.go
  pkg/test/storage.go
Labels: cncf-cla: yes, lgtm, size/L

#1090 deps: bump to go 1.22
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1085 chore: Adding a drift test and cleanup on wording
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodepool/hash/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1071 kustomize patchesStrategicMerge is deprecated, use patches instead.
  hack/install-kwok.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1094 test: Expanded Static drift testing to all `NodeClaimTemplate` fields
  pkg/controllers/nodeclaim/disruption/drift_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1099 fix: Check node readiness before force terminating
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1103 chore: Drop CloudProvider delete call from Node termination
  pkg/controllers/node/termination/controller.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1112 docs: adding supported cloud providers to readme
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1128 cherrypick(v0.34.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1129 cherrypick(v0.33.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1127 cherrypick(v0.35.x): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1125 fix: Adjust duration validation to include format for `1h10m`
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1126 chore: Remove finalizer with `Update()` instead of `Patch()`
  pkg/controllers/nodeclaim/termination/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1132 chore: Remove validation as covered by OpenAPI validation
  pkg/apis/v1beta1/nodepool_validation.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1138 chore: Changes to run e2e for private cluster
  pkg/test/deployment.go
  pkg/test/pods.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1131 cherrypick(v0.32): feat: Add Versioned for NodePool Hash to Prevent Drift on NodePool CRD Upgrade
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/nodepool.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/nodeclaim_drift_test.go
  pkg/controllers/nodepool/hash/controller.go
  pkg/controllers/nodepool/hash/nodepool_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/utils/nodepool/nodepool.go
Labels: cncf-cla: yes, lgtm, size/L

#1137 cherrypick(v0.34): fix: Adjust duration validation to include format for `1h10m`
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1136 cherrypick(v0.35): fix: Adjust duration validation to include format for `1h10m`
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1130 chore: Add comments on calls to kubeClient Update()
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/termination/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1142 chore: nit spelling fix
  pkg/controllers/disruption/multinodeconsolidation.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1146 feat: Get the GVK of the supported NodeClasses as part of the CloudProvider interface
  kwok/cloudprovider/cloudprovider.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1141 fix: Change type to hash on KubeReserved and SystemReserved
  hack/validation/kubelet.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodeclaim_validation.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
  pkg/apis/v1beta1/nodeclaim_validation_webhook_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L
