Repository kubernetes-sigs/karpenter, pull requests merged in 2024-01, with the labels that each got.

#913 ci: Drop `kind/support` from exempt and only use kind labels for exemption
  .github/workflows/stale.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#906 feat: add kwok install hack script
  Makefile
  hack/install-kwok.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#923 fix: add manual nodeclaim update into cluster state for new nodes
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#925 fix: only include initialized towards the budget total
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#929 chore: Remove unneeded packages from toolchain
  hack/toolchain.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#930 fix: Fix data race in cluster state
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#899 chore: Update ephemeral taints logic and drop unmanaged check on nodes
  pkg/controllers/disruption/helpers.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/controllers/state/suite_test.go
  pkg/scheduling/taints.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#941 test: Add readiness and liveness pod options
  pkg/test/pods.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#905 RFC: add in kwok design living doc
  designs/kwok-provider.md
Labels: cncf-cla: yes, lgtm, approved, size/M

#768 docs: RFC on design for spot->spot consolidation
  designs/spot-consolidation.md
Labels: needs-review, cncf-cla: yes, lgtm, approved, size/L

#946 ci: run test suite for K8s 1.29
  .github/workflows/presubmit.yaml
  hack/toolchain.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/test/environment.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#904 feat: kwok cloud provider
  Makefile
  go.mod
  go.sum
  hack/install-kwok.sh
  hack/validation/kwok-requirements.sh
  kwok/README.md
  kwok/charts/Chart.yaml
  kwok/charts/README.md
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  kwok/charts/templates/_helpers.tpl
  kwok/charts/templates/aggregate-clusterrole.yaml
  kwok/charts/templates/clusterrole.yaml
  kwok/charts/templates/deployment.yaml
  kwok/charts/templates/poddisruptionbudget.yaml
  kwok/charts/templates/role.yaml
  kwok/charts/templates/rolebinding.yaml
  kwok/charts/templates/service.yaml
  kwok/charts/templates/serviceaccount.yaml
  kwok/charts/templates/servicemonitor.yaml
  kwok/charts/values.yaml
  kwok/cloudprovider/cloudprovider.go
  kwok/cloudprovider/const.go
  kwok/cloudprovider/helpers.go
  kwok/main.go
  pkg/controllers/disruption/orchestration/queue.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#956 BREAKING CHANGE: Disallow resources to be in the `NodePool`
  Makefile
  hack/validation/resources.sh
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#958 perf: improve scheduling with large numbers of nodes using hostname topologies
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/utils/pretty/pretty.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#959 perf: track empty domains separately in topology
  pkg/controllers/provisioning/scheduling/topologygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#960 feat: add disruption event for a fully blocking budget
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/events/events.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#965 chore: Adding cherry picked commits to `release-v0.32.x`
  hack/toolchain.sh
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/utils/pretty/pretty.go
Labels: cncf-cla: yes, lgtm, size/M

#969 chore: typo in compatibility
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/controllers/provisioning/scheduling/topologynodefilter.go
  pkg/scheduling/requirements.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#971 fix: fix kwok requirements cel
  hack/validation/kwok-requirements.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#972 docs: Fix zoom meeting time to be correct
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#973 test: add command and prestop into test pod options
  pkg/test/pods.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#962 update benchmark to have anti-affinity pods
  go.mod
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#975 feat: add nodeclaim name into orchestration initialization failures
  pkg/controllers/disruption/orchestration/queue.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#979 chore: Adding cherry picked commits to release-v0.33.x
  hack/toolchain.sh
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/utils/pretty/pretty.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#961 fix: don't mark cluster consolidated if constrained by budgets
  Makefile
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#981 feat: consider not ready nodes for budgets
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#980 feat: add uid for orchestration queue for logs
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/orchestration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M
