Repository kubernetes-sigs/karpenter, pull requests merged in 2024-04, with the labels that each got.

#1148 chore: Bump `NodePoolHashVersion`
  pkg/apis/v1beta1/nodepool.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1044 docs: RFC for contributor ladder guidelines
  contributing-guidelines.md
Labels: cncf-cla: yes, lgtm, approved, size/M

#1156 chore: Bump tejolote for v0.34.x
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1155 chore: Bump tejolote For v0.35.x
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1157 chore: Retract the Karpenter version due to a bad release
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1154 chore: Pin the release action for v0.32.x
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, lgtm

#1158 chore: Retract v0.35.3 and v0.34.4
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1166 chore: Bump `golang.org/x/net due` to a vulncheck failure
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/S

#1147 feat: Detect Drift on NodeClaims on changes to NodeClass
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/operator/operator.go
  pkg/utils/nodeclaim/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1164 chore: Add retryable error to cloud provider
  pkg/cloudprovider/types.go
  pkg/controllers/nodeclaim/termination/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1170 chore: Add method to ignore Retryable error
  pkg/cloudprovider/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1172 chore: Re-enqueue nodeclaim termination after 10s in case of retryable error
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodeclaim/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1108 test: Re-organize the requirement tests.
  pkg/scheduling/requirement_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/XXL

#1184 chore: Remove Cloudprovider from Consistency controller
  pkg/controllers/controllers.go
  pkg/controllers/nodeclaim/consistency/controller.go
  pkg/controllers/nodeclaim/consistency/nodeshape.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1191 Revert "chore: Drop CloudProvider delete call from Node termination"
  pkg/controllers/node/termination/controller.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1192 chore: Add retryable error handling to node termination
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1193 chore: Retry retrieving default namespace to reduce flakiness
  pkg/test/environment.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1183 chore: bump registration ttl log
  pkg/controllers/nodeclaim/lifecycle/liveness.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1180 fix: address disruption taint race condition
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1206 cherry-pick: address disruption taint race condition (#1180)
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1214 fix: Only log found provisionable pods with new nodeclaims
  pkg/controllers/provisioning/provisioner.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#936 docs(RFC): disruption controls by reason
  designs/disruption-controls-by-reason.md
Labels: cncf-cla: yes, lgtm, approved, size/L
