Repository kubernetes-sigs/karpenter, pull requests merged in 2024-11, with the labels that each got.

#1796 Fix pod metrics that don't get deleted when the pod is deleted
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/metrics/pod/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1798 doc: update alibabacloud repo link
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1797 chore: make leader election ID configurable
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1768 RFC: Node Auto Repair
  designs/node-repair.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#1787 feat: add instance type drift for instance types that are no longer discoverable
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/nodeclaim/disruption/consolidation_test.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1801 Abstract prometheus metrics into interfaces
  go.mod
  go.sum
  pkg/cloudprovider/metrics/cloudprovider.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/orchestration/metrics.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/metrics/node/controller.go
  pkg/controllers/metrics/nodepool/controller.go
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/metrics.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/metrics.go
  pkg/controllers/nodeclaim/expiration/controller.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/liveness.go
  pkg/controllers/nodeclaim/lifecycle/metrics.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/metrics.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/metrics.go
  pkg/metrics/constants.go
  pkg/metrics/metrics.go
  pkg/metrics/store.go
  pkg/metrics/suite_test.go
  pkg/operator/operator.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1773 chore: Update max delay for NodeClaim lifecycle controller
  pkg/controllers/nodeclaim/lifecycle/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1807 fix: ensure node leases aren't leaked
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/initialization_test.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1808 feat: Add status conition controller for node objects
  go.mod
  go.sum
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1809 chore: Add unfinished_work_seconds metric
  pkg/controllers/provisioning/scheduling/metrics.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1811 chore: create new error type to wrap message and error
  pkg/cloudprovider/types.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/launch_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1812 chore: Convert `karpenter_scheduler_unfinished_work_seconds` to seconds
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1814 chore: Bump operatorpkg to include object based metrics
  go.mod
  go.sum
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1817 chore: increase bucket sizes for pod scheduling metrics
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/state/metrics.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1815 add cluster-api provider to readme
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1819 perf: Unregister the topology domain when failing NodeClaim creation
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1821 chore: Update kwok chart to latest
  Makefile
  kwok/charts/README.md
  kwok/charts/values.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1823 perf: Drop unneeded recalculation for resources and available
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/utils/resources/resources.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1824 perf: Pre-filter instance types on nodepool requirements
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/instance_selection_test.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1822 perf: Don't reparse selector on each toplogy select check
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1820 perf: Improve TopologyGroup node domain iteration
  pkg/controllers/provisioning/scheduling/topology_test.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1825 perf: Cache the pod request calculation in memory
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/queue.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1793 feat: Node Repair implementation
  kwok/cloudprovider/cloudprovider.go
  kwok/main.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
  pkg/controllers/controllers.go
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/health/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1827 perf: Cache taints for existing nodes
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1830 chore: Remove a controller that was used for testing
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1833 chore: Fix undecided time naming
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/metrics/pod/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1834 ci: Drop running kind jobs on main until they are green
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1832 chore: Remove Eventual Disruption cloud provider interface
  .gitignore
  hack/kwok/requirements.sh
  kwok/apis/v1alpha1/kwoknodeclass.go
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  kwok/cloudprovider/cloudprovider.go
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_budgets_test.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/suite_test.go
  test/suites/perf/disruption_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1835 chore: fix nodeclaim going unknown during instance termination
  pkg/utils/termination/termination.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/S

#1836 chore: Add pod scheduled prometheus label
  pkg/controllers/metrics/pod/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1831 chore: Limit Node Repair based by Nodepool
  pkg/controllers/controllers.go
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/health/events.go
  pkg/controllers/node/health/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1845 test: ensure NodeClaim root condition reamains known during termination
  pkg/utils/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1843 deps: bump operatorpkg
  go.mod
  go.sum
  pkg/test/metadata.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1854 fix: spurious disruption budget eventing
  pkg/controllers/disruption/helpers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1853 fix: hydration race for terminating nodes
  pkg/controllers/controllers.go
  pkg/controllers/node/hydration/controller.go
  pkg/controllers/node/hydration/suite_test.go
  pkg/controllers/nodeclaim/hydration/controller.go
  pkg/controllers/nodeclaim/hydration/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/hydration.go
  pkg/utils/node/node.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1855 chore: Bump operatorpkg with adding additional labels to status condition controllers
  go.mod
  go.sum
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1856 chore: Bump `github.com/awslabs/operatorpkg` to latest
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved
