Repository kubernetes-sigs/karpenter, pull requests merged in 2024-06, with the labels that each got.

#1291 Revert "chore(deps): revert dependabot bumps"
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/M

#1299 chore: update go to 1.22.4
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1298 chore: replace custom utils functions with k8s.io/kubernetes library
  go.mod
  go.sum
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/state/cluster.go
  pkg/utils/pod/scheduling.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1295 chore: fix up kwok cloud provider
  Makefile
  hack/validation/kwok-requirements.sh
  kwok/apis/apis.go
  kwok/apis/crds/kwok.karpenter.sh_kwoknodeclasses.yaml
  kwok/apis/v1alpha1/kwoknodeclass.go
  kwok/apis/v1alpha1/kwoknodeclass_status.go
  kwok/apis/v1alpha1/zz_generated.deepcopy.go
  kwok/charts/README.md
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  kwok/charts/crds/kwok.karpenter.sh_kwoknodeclasses.yaml
  kwok/charts/templates/clusterrole-kwok.yaml
  kwok/charts/values.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1289 chore: Convert singleton reconcilers to operatorpkg
  go.mod
  go.sum
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/expiration_test.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/metrics/node/controller.go
  pkg/controllers/metrics/node/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/state/informer/nodepool.go
  pkg/operator/controller/controller.go
  pkg/operator/operator.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1302 Revert "chore: replace custom utils functions with k8s.io/kubernetes"
  go.mod
  go.sum
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/state/cluster.go
  pkg/utils/pod/scheduling.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1304 fix: allow single character status condition reason
  hack/validation/status.sh
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1307 fix bug in printing truncated maps
  go.mod
  pkg/utils/pretty/pretty.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1296 chore: move disruption and pdb utils and factor isDisruptable into cluster state
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/events/events.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/nodeclaim/consistency/termination.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/state/statenode.go
  pkg/utils/disruption/disruption.go
  pkg/utils/pdb/pdb.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1309 test: remove timeout tests that weren't working
  pkg/controllers/disruption/consolidation_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1312 chore: Drop unused scheduler context argument
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1313 chore: Remove `Get()` in offerings in favor of `Compatible()`
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/provisioning/scheduling/instance_selection_test.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1311 feat: promote drift to stable
  kwok/charts/README.md
  kwok/charts/templates/deployment.yaml
  kwok/charts/values.yaml
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1317 chore: fix kwok offerings to use new requirements
  kwok/cloudprovider/helpers.go
  kwok/cloudprovider/instance_types.json
  kwok/tools/gen_instance_types.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1318 chore: add 1.30 into presubmit versions
  .github/workflows/presubmit.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1279 chore: add kwok e2e environment utils
  .github/actions/install-prometheus/action.yaml
  .github/actions/install-prometheus/values.yaml
  .github/actions/install-pyroscope/action.yaml
  .github/dependabot.yaml
  .github/workflows/kind-e2e.yaml
  .github/workflows/test-kind.yaml
  Makefile
  kwok/charts/templates/clusterrole-kwok.yaml
  kwok/cloudprovider/helpers.go
  kwok/cloudprovider/instance_types.json
  test/README.md
  test/pkg/debug/events.go
  test/pkg/debug/monitor.go
  test/pkg/debug/node.go
  test/pkg/debug/nodeclaim.go
  test/pkg/debug/pod.go
  test/pkg/debug/setup.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/monitor.go
  test/pkg/environment/common/setup.go
  test/suites/perf/scheduling_test.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1195 chore: Wait for instance termination before deleting nodeclaim
  pkg/apis/v1beta1/nodeclaim_status.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/termination/controller.go
  pkg/controllers/nodeclaim/termination/metrics.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/metrics/metrics.go
  pkg/test/expectations/expectations.go
  pkg/utils/node/node.go
  pkg/utils/node/suite_test.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/termination/suite_test.go
  pkg/utils/termination/termination.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, needs-ok-to-test

#1319 fix: kwok offerings to use correct requirements
  kwok/cloudprovider/helpers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1322 fix: add deletiontimestamp check for kwok termination
  kwok/cloudprovider/cloudprovider.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1320 test: update node termination test to model eventual removal
  pkg/controllers/node/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1328 chore: fix kwok api version group
  kwok/README.md
  kwok/apis/apis.go
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/apis/v1alpha1/doc.go
  kwok/apis/v1alpha1/labels.go
  kwok/apis/v1alpha1/register.go
  kwok/charts/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/kwok.karpenter.sh_kwoknodeclasses.yaml
  kwok/charts/templates/clusterrole-kwok.yaml
  kwok/cloudprovider/helpers.go
  kwok/main.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#991 feat: disruption controls by reason
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  kwok/charts/values.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/events/events.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
  pkg/controllers/state/cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1324 test: add test timestamp collector
  pkg/test/pods.go
  test/pkg/debug/collector.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/setup.go
  test/suites/perf/scheduling_test.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1303 docs: add RFC on making expiration forceful
  designs/forceful-expiration.md
  designs/images/forceful-expiration.png
  designs/images/graceful-expiration.png
Labels: cncf-cla: yes, lgtm, approved, size/M

#1335 test: add output_dir env variable for timestamp exports
  test/pkg/debug/collector.go
  test/pkg/environment/common/environment.go
  test/suites/perf/scheduling_test.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1345 fix: logger print KubeConfig error
  pkg/operator/operator.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1349 chore: Add IsCompatible
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/types.go
  pkg/scheduling/requirements.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1344 chore: Increase nodeClaim spec.requirements to 100
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1332 chore: Drop event recorder from provisioning controllers
  pkg/controllers/controllers.go
  pkg/controllers/provisioning/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1357 chore: Update storage version to v1beta1 APIs
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodepool.go
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1363 chore: encapsulate state.Cluster inside of NewControllers
  kwok/main.go
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1364 chore: Simplify scheme to use clientgoscheme
  pkg/apis/apis.go
  pkg/apis/v1/doc.go
  pkg/apis/v1/labels.go
  pkg/apis/v1/register.go
  pkg/apis/v1/suite_test.go
  pkg/apis/v1/taints.go
  pkg/apis/v1beta1/doc.go
  pkg/apis/v1beta1/labels.go
  pkg/apis/v1beta1/register.go
  pkg/apis/v1beta1/suite_test.go
  pkg/apis/v1beta1/taints.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/leasegarbagecollection/suite_test.go
  pkg/controllers/metrics/node/suite_test.go
  pkg/controllers/metrics/nodepool/suite_test.go
  pkg/controllers/metrics/pod/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/termination/suite_test.go
  pkg/controllers/nodepool/counter/suite_test.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/suite_test.go
  pkg/operator/operator.go
  pkg/operator/scheme/scheme.go
  pkg/test/environment.go
  pkg/test/expectations/expectations.go
  pkg/utils/node/suite_test.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/suite_test.go
  pkg/utils/termination/suite_test.go
  pkg/webhooks/webhooks.go
  test/pkg/debug/monitor.go
  test/pkg/environment/common/environment.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1333 BREAKING: revert back to forceful expiration by default
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim_status.go
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_budgets_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/expiration_test.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/nodeclaim/disruption/expiration.go
  pkg/controllers/nodeclaim/disruption/expiration_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/liveness.go
  pkg/metrics/metrics.go
  test/pkg/environment/common/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1359 chore: Make NodeClaim Spec Immutable on v1 API
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/v1/nodeclaim.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1367 feat: Adding printer columns on v1 NodeClaims
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/v1/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1358 chore: Remove kubelet configuration from the v1 APIs
  hack/validation/kubelet.sh
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodeclaim_validation.go
  pkg/apis/v1/nodeclaim_validation_cel_test.go
  pkg/apis/v1/nodeclaim_validation_webhook_test.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/nodepool_validation_webhook_test.go
  pkg/apis/v1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#1369 feat: Add karpenter client-go metrics
  go.mod
  go.sum
  pkg/operator/operator.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1360 chore: Update `nodeClassRef` to be Group instead of APIVersion
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1361 chore: Remove Resource field from the NodePool API
  Makefile
  hack/mutation/nodepool.sh
  hack/validation/resources.sh
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodepool_validation.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/apis/v1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1368 chore: Simplify scheme to use clientgoscheme for KWOK
  kwok/apis/apis.go
  kwok/apis/v1alpha1/doc.go
  kwok/apis/v1alpha1/labels.go
  kwok/apis/v1alpha1/register.go
  kwok/apis/v1alpha1/zz_generated.deepcopy.go
  kwok/cloudprovider/cloudprovider.go
  test/pkg/environment/common/environment.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L
