Repository kubernetes-sigs/karpenter, pull requests merged in 2024-10, with the labels that each got.

#1716 fix: Fix webhook owner reference causing ArgoCD leak
  go.mod
  go.sum
  pkg/controllers/webhookownerreference/controller.go
  pkg/controllers/webhookownerreference/suite_test.go
  pkg/operator/operator.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1729 fix: Fix webhook owner ref on v0.36.x (cherry-pick)
  go.mod
  go.sum
  pkg/controllers/webhookownerreference/controller.go
  pkg/controllers/webhookownerreference/suite_test.go
  pkg/operator/operator.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1730 fix: Fix webhook owner ref on v0.35.x (cherry-pick)
  go.mod
  go.sum
  pkg/controllers/webhookownerreference/controller.go
  pkg/controllers/webhookownerreference/suite_test.go
  pkg/operator/operator.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1731 fix: Fix webhook owner ref on v0.34.x (cherry-pick)
  go.mod
  go.sum
  pkg/controllers/webhookownerreference/controller.go
  pkg/controllers/webhookownerreference/suite_test.go
  pkg/operator/operator.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1732 fix: Fix webhook owner ref on v0.33.x (cherry-pick)
  go.mod
  go.sum
  pkg/controllers/webhookownerreference/controller.go
  pkg/controllers/webhookownerreference/suite_test.go
  pkg/operator/operator.go
  pkg/webhooks/webhooks.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1735 perf: don't include terminated nodes in budget
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1728 fix: spurious logging from migration controller
  pkg/controllers/migration/crd/controller.go
  pkg/controllers/migration/crd/suite_test.go
  pkg/controllers/migration/resource/controller.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1736 cherry-pick: don't include terminated nodes in budget (#1735)
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1739 fix: correct error type for NodeClaim helpers
  pkg/utils/node/node.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1738 chore: Add pod metrics
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/metrics/pod/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1609 doc: make kwok docs better for local development
  kwok/README.md
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1751 chore: remove dead disruptable code
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1758 chore: Scope role down to needed permissions
  kwok/charts/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1766 fix: clarify state node logging
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1763 fix: check for nil pointer dereference
  pkg/controllers/disruption/multinodeconsolidation.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1760 RFC: Capacity Reservations
  designs/capacity-reservations.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#1788 feat: add log for scheduling progress for long running scheduling sim…
  pkg/controllers/controllers.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1790 fix: check for nil pointer dereference (#1763)
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#1698 Implemented UnschedulablePodsCount metric
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/metrics.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#1794 fix: dedupe expiration reconciliations
  pkg/controllers/nodeclaim/expiration/controller.go
  pkg/controllers/nodeclaim/expiration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M
