Repository kubernetes-sigs/karpenter, pull requests merged in 2024-02, with the labels that each got.

#989 test: Add Should(Succeed()) to EventuallyExpectTerminating
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#988 fix: allow disruption when considering past disruption commands
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#933 fix: emit pod nomination events and add provisioning node tainted trigger controller
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/types.go
  pkg/controllers/provisioning/controller.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#569 feat: Support PodRequests calculations for initContainers with restar…
  kwok/cloudprovider/helpers.go
  pkg/cloudprovider/fake/instancetype.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/test/pods.go
  pkg/utils/resources/resources.go
  pkg/utils/resources/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#998 fix: Use UUID as a precondition when calling the eviction API
  go.mod
  go.sum
  kwok/main.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1000 chore: Add note on how Karpenter responds to Unschedulable
  pkg/utils/pod/scheduling.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1006 fix: Fix budget validation through CEL
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#966 RFC: Propose `minValues` to enforce Flexibility on NodeClaim Requests
  designs/nodepool-requirement-flexibility.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#1002 fix: Use UUID as a precondition when calling the eviction API (#998)
  go.mod
  go.sum
  pkg/controllers/controllers.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1001 fix: Use UUID as a precondition when calling the eviction API (#998)
  go.mod
  go.sum
  pkg/controllers/controllers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/machine_test.go
  pkg/controllers/node/termination/nodeclaim_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L

#982 perf: increase scheduler performance
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/scheduling/requirements.go
  pkg/scheduling/requirements_test.go
  pkg/utils/resources/resources.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#952 feat: adding karpenter_state_nodes_total metric and karpenter_state_synced
  pkg/controllers/state/cluster.go
  pkg/controllers/state/metrics.go
  pkg/controllers/state/suite_test.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1008 ci: Drop `--ginkgo.timeout` and add `--ginkgo.randomize-all` CLI arg for Makefile target
  Makefile
  pkg/controllers/leasegarbagecollection/controller.go
  pkg/controllers/leasegarbagecollection/metrics.go
  pkg/controllers/leasegarbagecollection/suite_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/operator/options/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1011 fix: Ensure that cluster_state_synced metric gets set if function exits early
  pkg/controllers/state/cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1012 fix: Fix an issue where the instanceTypes aren't sorted before truncating it for spot-to-spot consolidation.
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1010 fix: Add locking/unlocking to set `Add()`, `Delete()`, and `Reset()`
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1017 test: Fix data race while calling `Reset()` in CI testing
  pkg/controllers/node/termination/terminator/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1020 chore: Adding cherry picked commits to release-v0.34.x
  go.mod
  go.sum
  kwok/main.go
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodepool.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/controllers/provisioning/suite_test.go
  pkg/scheduling/requirements.go
  pkg/scheduling/requirements_test.go
  pkg/utils/resources/resources.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, needs-ok-to-test

#1023 test: Fix flake in requeueAfter returned from expiration disruption
  pkg/controllers/nodeclaim/disruption/expiration_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1022 chore: Report node allocatable capacity as part of log on register/initialize
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1025 chore: Add pod/node count to metrics and logs for disruption
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptynodeconsolidation.go
  pkg/controllers/disruption/expiration.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1032 fix: add missing print directive
  pkg/controllers/disruption/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#963 feat: Add support for minValues in requirement for scheduling, consolidation layer and corresponding API changes.
  kwok/cloudprovider/cloudprovider.go
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodeclaim_validation.go
  pkg/apis/v1beta1/nodeclaim_validation_cel_test.go
  pkg/apis/v1beta1/nodeclaim_validation_webhook_test.go
  pkg/apis/v1beta1/nodepool_validation_cel_test.go
  pkg/apis/v1beta1/nodepool_validation_webhook_test.go
  pkg/apis/v1beta1/zz_generated.deepcopy.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/fake/instancetype.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodepool/hash/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/instance_selection_test.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/scheduling/topology_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/suite_test.go
  pkg/scheduling/requirement.go
  pkg/scheduling/requirement_test.go
  pkg/scheduling/requirements.go
  pkg/scheduling/requirements_test.go
  pkg/test/nodeclaim.go
  pkg/test/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/XXL

#1037 test: Fix missed `BeTrue()` in testing
  pkg/controllers/node/termination/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1035 chore: Patch in race condition for eviction queue fixes to v0.32.x
  pkg/controllers/node/termination/machine_test.go
  pkg/controllers/node/termination/nodeclaim_test.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
Labels: cncf-cla: yes, lgtm, size/M

#1036 chore: Patch in race condition for eviction queue fixes to v0.33.x
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1039 test: Ensure that MaxInstanceTypes is reset at the beginning of each test
  pkg/controllers/provisioning/scheduling/instance_selection_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1041 chore: Reject NodePools and NodeClaims if they don't have spec
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1beta1/nodeclaim.go
  pkg/apis/v1beta1/nodepool.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1043 perf: don't inject new loggers in GetVolumes
  pkg/scheduling/volumeusage.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#999 chore: Drop simulation mode in favor of NopLogger and Recording scheduling results
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/operator/logging/logging.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1053 test: Add minValues to the NodePool requirements for benchmark testing.
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M
