Repository kubernetes-sigs/karpenter, pull requests merged in 2024-12, with the labels that each got.

#1860 Remove PDB check in consistency controller
  pkg/controllers/nodeclaim/consistency/controller.go
  pkg/controllers/nodeclaim/consistency/suite_test.go
  pkg/controllers/nodeclaim/consistency/termination.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1838 docs: add gcp provider
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1727 fix: Fix handling for multiple Daemonset nodeAffinity selectorTerms
  pkg/controllers/provisioning/scheduling/preferences.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1864 chore: Bump `github.com/awslabs/operatorpkg` to latest
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1868 chore: Add initialized label key to metric labels
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1863 Fix: Set Karpenter Consolidation Timeouts to zero
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1862 fix: Lower casing disruption count metric on reason label
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/health/suite_test.go
  pkg/controllers/nodeclaim/expiration/controller.go
  pkg/utils/pretty/pretty.go
  pkg/utils/pretty/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1869 fix: Ensure we keep observedGeneration up-to-date even when resource has completed
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/launch.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1871 fix: move pod ack to when pod is first seen by Karpenter
  pkg/controllers/controllers.go
  pkg/controllers/provisioning/controller.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1875 chore: Update issue stale-out to use triage flow
  .github/workflows/stale.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M

#1877 fix: nodeclass label validation for kwok CRDs
  hack/kwok/requirements.sh
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1874 chore: clarify disruption candidate conditional
  pkg/controllers/disruption/types.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1888 chore: Avoid multiple logs messages for the node health controller
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/health/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1891 feat: add event for prefiltered instance types
  pkg/controllers/provisioning/scheduling/events.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1847 feat: allow custom kwok instance-types at runtime
  kwok/README.md
  kwok/cloudprovider/helpers.go
  kwok/main.go
  kwok/options/options.go
Labels: lifecycle/stale, cncf-cla: yes, lgtm, approved, ok-to-test, size/M
