Repository kubernetes-sigs/karpenter, pull requests merged in 2025-07, with the labels that each got.

#2337 fix: Fix re-retrieving object on retry
  pkg/controllers/disruption/queue.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2338 fix: Fix overriding error with patch call
  pkg/controllers/node/termination/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2356 fix: no longer allow the same hostname to take multiple capacity
  pkg/controllers/provisioning/scheduling/reservationmanager.go
  pkg/controllers/provisioning/scheduling/reservationmanager_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#2363 fix: update provider ID to ensure that Cloud Provider tests pass
  test/suites/regression/nodeclaim_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2365 chore: promote ReservedCapacity feature gate to beta
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2366 fix: flakiness in expiration tests
  test/suites/regression/expiration_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/S

#2367 test: Bump the termination time for the deletion timestamp
  pkg/controllers/node/termination/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2371 fix: no longer allow the same hostname to take multiple capacity (#2356)
  pkg/controllers/provisioning/scheduling/reservationmanager.go
  pkg/controllers/provisioning/scheduling/reservationmanager_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2372 refactor: Update disruption testing from PR comments
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2349 feat: (BREAKING) addition of launch timeout for nodeclaim lifecycle
  pkg/controllers/nodeclaim/lifecycle/liveness.go
  pkg/controllers/nodeclaim/lifecycle/liveness_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2265 chore: Consider node.kubernetes.io/not-ready:NoExecute as ephemeral
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/suite_test.go
  pkg/scheduling/taints.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#2166 docs: Node Overlay RFC
  designs/node-overlay.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#2396 docs: Add IBM Cloud provider
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2399 fix: rate limit eviction when PDBs are blocking
  pkg/controllers/node/termination/terminator/eviction.go
  pkg/controllers/node/termination/terminator/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2296 feat: Add the Node Overlay CRD
  hack/validation/requirements.sh
  kwok/charts/crds/karpenter.sh_nodeoverlays.yaml
  pkg/apis/apis.go
  pkg/apis/crds/karpenter.sh_nodeoverlays.yaml
  pkg/apis/v1/labels.go
  pkg/apis/v1alpha1/doc.go
  pkg/apis/v1alpha1/labels.go
  pkg/apis/v1alpha1/nodeoverlay.go
  pkg/apis/v1alpha1/nodeoverlay_status.go
  pkg/apis/v1alpha1/nodeoverlay_validation.go
  pkg/apis/v1alpha1/nodeoverlay_validation_test.go
  pkg/apis/v1alpha1/suite_test.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/test/expectations/expectations.go
  pkg/test/nodeoverlay.go
  test/pkg/environment/common/setup.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#2400 chore: ignore pods that use unsupported provisioner in the storageClass
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/scheduling/volumetopology.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M
