Repository kubernetes-sigs/karpenter, pull requests merged in 2025-06, with the labels that each got.

#2274 fix: Fix node owner reference update
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/utils/nodeclaim/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2272 perf: Be more resilient to deletion failures in disruption controller
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2283 chore: Ensure we can stand up multiple partitions with kwok
  Makefile
  hack/install-kwok.sh
Labels: cncf-cla: yes, lgtm, approved, size/M

#2285 chore: Inject resources into Kwok through a patch
  hack/install-kwok.sh
Labels: cncf-cla: yes, lgtm, approved, size/S

#2284 chore: Update NodeClaim E2E test to only replace one status condition
  kwok/cloudprovider/cloudprovider.go
  test/pkg/environment/common/expectations.go
  test/suites/regression/nodeclaim_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2302 chore: Only log that the command succeeded when it actually did
  pkg/controllers/disruption/orchestration/queue.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2303 docs: Add Bizfly Cloud provider
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#2308 chore: Use cluster state to check replacement NodeClaim existence
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/orchestration/suite_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/state/cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2305 chore: Refactor Orchestration Queue and Handle Mark/Unmark Deletion in Queue
  go.mod
  pkg/controllers/controllers.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/orchestration/metrics.go
  pkg/controllers/disruption/queue.go
  pkg/controllers/disruption/queue_test.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation_test.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#2324 perf: Reduce multiple patch calls in instance termination
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
  pkg/utils/termination/suite_test.go
  pkg/utils/termination/termination.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2336 fix: add helm rbac for kwok-provider to update finalizers
  kwok/charts/templates/clusterrole.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2328 feat: configure CRD status operator with larger histogram buckets
  go.mod
  go.sum
  pkg/controllers/controllers.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test
