Repository kubernetes-sigs/karpenter, pull requests merged in 2025-05, with the labels that each got.

#2167 test: Migrate the Chaos suite test from the AWS Karpenter Provider
  test/pkg/environment/common/environment.go
  test/suites/integration/chaos_test.go
  test/suites/integration/perf_test.go
  test/suites/integration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2184 ci: Enable Kind Cluster Testing on PR Merge
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2125 fix: Allow disabling syncing taints from nodeclaims to nodes (with node label)
  pkg/apis/v1/labels.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/L

#2189 test: Apply KWOK requirement to only work with KWOK nodeclass
  test/suites/integration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2196 chore: Fix event log line for a pointer
  pkg/controllers/node/termination/terminator/events/events.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2197 test: Migrate the Integration suite test from the AWS Karpenter Provider
  Makefile
  kwok/charts/README.md
  kwok/charts/templates/deployment.yaml
  kwok/charts/values.yaml
  kwok/cloudprovider/cloudprovider.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/suites/integration/intagration_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2190 test: Update E2E tests to disable expiration for new nodes that have expired
  test/suites/integration/chaos_test.go
  test/suites/integration/expiration_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2204 ci: Temporarily Disable Karpenter KPI Analysis Package
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#2205 ci: Temporarily Disable Karpenter KPI actions
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#2164 fix: add runtime validation for requirements with known values
  pkg/apis/v1/labels.go
  pkg/apis/v1/nodeclaim_validation.go
  pkg/apis/v1/nodepool_validation.go
  pkg/apis/v1/nodepool_validation_cel_test.go
  pkg/controllers/nodepool/validation/controller.go
  pkg/controllers/nodepool/validation/suite_test.go
  pkg/controllers/provisioning/provisioner.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2182 fix: should consider pending pods with preferred nodeAffinity when making provisioning decisions
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#2193 test: Migrate the NodeClaim suite test from the AWS Karpenter Provider
  designs/karpenter-integration-testing.md
  kwok/cloudprovider/cloudprovider.go
  test/pkg/environment/common/expectations.go
  test/suites/integration/nodeclaim_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2207 chore: Remove mismatch with deps used for E2E tests
  .github/workflows/kind-e2e.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2195 test: Migrate the Drift suite test from the AWS Karpenter Provider
  hack/install-kwok.sh
  hack/kwok/stages/pod-unhealthy.yaml
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/setup.go
  test/suites/integration/drift_test.go
  test/suites/integration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2209 test: Use Foreground deletion to cleanup our tests
  test/pkg/environment/common/setup.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2214 test: Add default disruption budgets for the drifted initialized failure tests
  test/suites/integration/drift_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2215 chore: Fix scheduling timeout error check
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2216 test: Block NodeClaim registration for E2E tests using validating admission policy
  Makefile
  test/pkg/environment/common/expectations.go
  test/suites/integration/drift_test.go
  test/suites/integration/nodeclaim_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2208 chore: Update the testing README to define mechanism for cloud provider to run the integrated testing
  test/README.md
Labels: cncf-cla: yes, lgtm, approved, size/L

#2173 test: Migrate the Termination suite test from the AWS Karpenter Provider
  hack/kwok/stages/pod-delete.yaml
  pkg/test/pods.go
  test/pkg/environment/common/expectations.go
  test/suites/integration/termination_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2225 test: Use Pod Metadata field for test objects
  pkg/test/daemonsets.go
  pkg/test/deployment.go
  pkg/test/statefulsets.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2224 perf: Speed-up resource checking for existing nodes
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/utils/resources/resources.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2226 perf: Poll for DaemonSet resources rather than watching
  pkg/controllers/state/informer/daemonset.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2229 test: Lower resource requests for NodeClaim test
  test/suites/integration/nodeclaim_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2210 fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/nodeclaim/consistency/termination.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/test/pods.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  pkg/utils/node/node.go
  pkg/utils/pdb/pdb.go
  pkg/utils/pdb/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2211 fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/test/pods.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  pkg/utils/node/node.go
  pkg/utils/pdb/pdb.go
  pkg/utils/pdb/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2212 fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/test/pods.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  pkg/utils/node/node.go
  pkg/utils/pdb/pdb.go
  pkg/utils/pdb/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2213 fix: don't provision unnecessary capacity for pods which can't move to a new node (#2033)
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/state/statenode.go
  pkg/test/pods.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  pkg/utils/node/node.go
  pkg/utils/pdb/pdb.go
  pkg/utils/pdb/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2232 perf: Don't deepcopy inside of watch handler functions
  pkg/utils/nodeclaim/nodeclaim.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2231 test: Add random name string for NodePool and NodeClass
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/suites/integration/nodeclaim_test.go
  test/suites/integration/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2234 test: Update E2E testing suite to be named Regression
  test/suites/regression/chaos_test.go
  test/suites/regression/drift_test.go
  test/suites/regression/expiration_test.go
  test/suites/regression/intagration_test.go
  test/suites/regression/nodeclaim_test.go
  test/suites/regression/perf_test.go
  test/suites/regression/suite_test.go
  test/suites/regression/termination_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2206 fix: allow non-churn empty nodes to be disrupted
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
  pkg/controllers/nodeclaim/disruption/drift.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2233 perf: Only deep copy nodes during GetCandidates once
  pkg/controllers/disruption/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#2239 feat: add metrics for disruption candidate validation
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/controller.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/emptiness_test.go
  pkg/controllers/disruption/metrics.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/orchestration/metrics.go
  pkg/controllers/disruption/orchestration/queue.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/validation.go
  pkg/controllers/disruption/validation_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2241 perf: Only call .Available() once which prevents duplicate allocs
  pkg/controllers/provisioning/scheduling/existingnode.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#2244 docs: update issue triage meeting schedule
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2240 test: deflake NodeClaim and presubmit tests
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/validation_test.go
  test/suites/regression/nodeclaim_test.go
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/M

#2250 perf: Improve OrderByPrice performance
  pkg/cloudprovider/types.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2251 test: add validating admission policy for nodeclass status
  test/pkg/environment/common/expectations.go
  test/suites/regression/nodeclaim_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1876 feat: drain and volume detachment status conditions
  pkg/apis/v1/nodeclaim_status.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
  pkg/controllers/node/termination/terminator/events/events.go
  pkg/controllers/node/termination/terminator/suite_test.go
  pkg/controllers/node/termination/terminator/terminator.go
  pkg/events/reason.go
  pkg/utils/node/node.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2260 perf: Don't deep-copy nodes and nodeclaims in our synced check
  pkg/controllers/state/cluster.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2262 chore: Fix getting current script directory in install-kwok.sh
  hack/install-kwok.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2259 chore: Update pod metrics when pod is completed
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/metrics/pod/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#2263 fix: Correctly build nodepool mapping for complex clusters
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/suite_test.go
  pkg/controllers/state/cluster.go
  pkg/test/expectations/expectations.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M, do-not-merge/hold

#2266 fix: fail open for missing nodeclaims in termination
  pkg/controllers/node/termination/controller.go
  pkg/controllers/node/termination/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2270 perf: Parallelize disruption execution actions
  pkg/controllers/disruption/controller.go
  pkg/controllers/state/statenode.go
Labels: cncf-cla: yes, lgtm, approved, size/M
