Repository kubernetes-sigs/karpenter, pull requests merged in 2025-03, with the labels that each got.

#2040 test: Fix `ConsolidationState()` test failure in state testing (#1957)
  .github/actions/install-deps/action.yaml
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2038 test: Fix `ConsolidationState()` test failure in state testing (#1957) 1.2.x
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2051 chore: Backport #1958 to v1.0.x release branch
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2050 chore: Refactor some detials of disruption reason condition
  pkg/controllers/disruption/controller.go
  pkg/controllers/node/termination/terminator/events/events.go
  pkg/controllers/node/termination/terminator/eviction.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1910 chore: RFC for NodeRegistrationHealthy Status Condition on NodePool
  designs/images/noderegistrationhealthy-nodepools1.png
  designs/images/noderegistrationhealthy-nodepools2.png
  designs/noderegistrationhealthy-status-condition.md
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/M

#2055 fix: update CEL validation for expireAfter and consolidateAfter fields to block invalid values like 1hr
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1/nodeclaim.go
  pkg/apis/v1/nodeclaim_validation_cel_test.go
  pkg/apis/v1/nodepool.go
  pkg/apis/v1/nodepool_validation_cel_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1846 feat: Expose drifted nodeclaim condition status to printer column output
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/v1/nodeclaim.go
Labels: lifecycle/closed, lifecycle/stale, cncf-cla: yes, size/XS, lgtm, approved

#2060 test: Improved Cluster State Test Suite duration from 727 seconds to 71 seconds
  .gitignore
  pkg/controllers/state/suite_test.go
  pkg/test/environment.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2061 fix: update range in test
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2062 docs: Add cleanup section to the contributor ladder doc
  contributing-guidelines.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2068 chore: Add node registration delay option to Kwok
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/apis/v1alpha1/kwoknodeclass.go
  kwok/apis/v1alpha1/zz_generated.deepcopy.go
  kwok/cloudprovider/cloudprovider.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2058 chore: Move bwagner5 to emeritus maintainer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2064 chore: Remove jackfrancis from karpenter-reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2074 fix: missing requirements in scheduling error log
  pkg/controllers/provisioning/scheduling/nodeclaim.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2053 feat: add requirement keys of KWOK instance offerings to well-known labels
  kwok/cloudprovider/cloudprovider.go
  kwok/cloudprovider/helpers.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#2035 perf: shuffle disruption candidates by nodepool
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/drift.go
  pkg/controllers/disruption/emptiness.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation.go
  pkg/controllers/disruption/singlenodeconsolidation_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/disruption/validation.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2081 chore: Bump operatorpkg to latest
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, approved, size/S

#2025 perf: respect multinode consolidation timeout in all cases
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/multinodeconsolidation.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#2086 test: add nodepool nodeclassref field indexer
  pkg/test/environment.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2087 chore: Bump `github.com/awslabs/operatorpkg` to latest
  go.mod
  go.sum
  pkg/controllers/nodeclaim/lifecycle/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2088 feat: Add Global Default Termination Grace Period Variable
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2100 fix: Create a separate leader config for different QPS/Burst
  pkg/operator/operator.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#2102 fix: address nodeclaims being repeatedly created when host ports for a pending pod would conflict with daemons
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2106 fix: don't need to deepcopy nodeclaim when lastPodEvent has not been set before the timeout
  pkg/controllers/nodeclaim/podevents/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
