Repository kubernetes-sigs/karpenter, pull requests merged in 2025-02, with the labels that each got.

#1934 chore: Update the README with update community meetings times
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#1957 test: Fix `ConsolidationState()` test failure in state testing
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1952 feat: Create Unhealthy Disrupted Nodeclaim Metric
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/health/metrics.go
  pkg/controllers/node/health/suite_test.go
  pkg/metrics/constants.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1948 perf: Capture InstanceTypeFilterErrors in error structs and don't print them until the end
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1953 perf: Don't create new sets when checking compatibility
  pkg/scheduling/requirement.go
  pkg/scheduling/requirements.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1949 chore: Add more scheduler logging for pods
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1950 perf: Cache requirements for pods alongside requests
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/queue.go
  pkg/controllers/provisioning/scheduling/scheduler.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1964 test: Ensure that we don't step the idle duration since this can cause the batcher to exit
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1966 perf: Reduce the memory overhead on cluster state `Synced()`
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1967 perf: Add event filter for NodeClaims that have resolved providerIDs
  pkg/controllers/nodepool/counter/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1971 chore: Bump go minor version to 1.23.6
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#1968 perf: Don't DeepCopy DaemonSet Pods
  pkg/controllers/state/cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1972 chore: Fix daemonset calculation bug
  pkg/controllers/state/cluster.go
  pkg/controllers/state/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1944 chore: Update nodeclaim finalization flow to not depend on cloudProvider.Get()
  pkg/cloudprovider/types.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
  pkg/utils/termination/suite_test.go
  pkg/utils/termination/termination.go
Labels: cncf-cla: yes, lgtm, approved, needs-ok-to-test, size/L

#1973 perf: Remove using `Difference()` from set creation
  pkg/scheduling/requirements.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1975 chore: Ensure that we implement `Unwrap` to support `errors.As`
  pkg/cloudprovider/suite_test.go
  pkg/cloudprovider/types.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#1980 chore: Bump controller-gen to the latest version
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S

#1982 chore: clear pod scheduling decisions if there are no valid nodepools
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1984 chore: fix spelling error in node health log
  pkg/controllers/node/health/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#852 feat: support new topologySpread scheduling constraints
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/existingnode.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/topology.go
  pkg/controllers/provisioning/scheduling/topology_test.go
  pkg/controllers/provisioning/scheduling/topologydomaingroup.go
  pkg/controllers/provisioning/scheduling/topologygroup.go
  pkg/controllers/provisioning/scheduling/topologynodefilter.go
  pkg/scheduling/taints.go
  pkg/utils/pod/scheduling.go
  test/pkg/environment/common/expectations.go
Labels: blocked, cncf-cla: yes, lgtm, approved, size/XXL

#1985 deps: bump go to 1.24.0
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1963 test: Expand KOWKNodeClass to Support Generic NodeClass for E2E tests
  go.mod
  test/pkg/environment/common/default_kowknodeclass.yaml
  test/pkg/environment/common/default_nodepool.yaml
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/setup.go
  test/suites/perf/scheduling_test.go
  test/suites/perf/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#1996 test: allow kwok provider deletion to terminate instance
  kwok/cloudprovider/cloudprovider.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1990 ci: fix flaky test for stale instance type drift
  Makefile
  pkg/controllers/nodeclaim/disruption/drift_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#1983 docs: add proxmox provider
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#2011 perf: check validity before constructing a new set of requirements
  pkg/controllers/provisioning/scheduling/existingnode.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2008 perf: remove the edit distance helper for identifying typos
  pkg/scheduling/requirements.go
  pkg/scheduling/requirements_test.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2013 perf: trade off less verbose errors for faster execution
  pkg/scheduling/requirements.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2012 perf: sort Pods by node name to allow re-use of scheduling requirements
  pkg/controllers/provisioning/scheduling/topology.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2000 ci: add a workflow semantic-pr
  .github/workflows/semantic-pr.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, needs-ok-to-test

#2010 test: increase Eventually timeout in e2e tests
  test/pkg/environment/common/environment.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1999 chore: Ensure that NodeClaim is always logged with Node
  pkg/controllers/node/health/controller.go
  pkg/controllers/node/hydration/controller.go
  pkg/controllers/node/termination/controller.go
  pkg/controllers/nodeclaim/consistency/controller.go
  pkg/controllers/nodeclaim/disruption/controller.go
  pkg/controllers/nodeclaim/expiration/controller.go
  pkg/controllers/nodeclaim/garbagecollection/controller.go
  pkg/controllers/nodeclaim/hydration/controller.go
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/initialization.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2015 fix: BREAKING put karpenter_ignored_pod_count metric under scheduler subsystem
  pkg/controllers/provisioning/scheduling/metrics.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#2019 test: Remove drifted reason on Reset() for `fake.CloudProvider`
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/controllers/nodeclaim/disruption/drift_test.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#1756 chore: Install toolchain files to location provided in KUBEBUILDER_ASSETS if set
  hack/toolchain.sh
Labels: lifecycle/closed, lifecycle/stale, cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#1991 fix: remove registration taint enforcement
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/events.go
  pkg/controllers/nodeclaim/lifecycle/initialization_test.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
  pkg/events/reason.go
Labels: cncf-cla: yes, approved, size/L

#2024 chore: Update the scheduling metric name to be `karpenter_pods_provisioning_scheduling_undecided_time_seconds`
  pkg/controllers/metrics/pod/controller.go
  pkg/controllers/metrics/pod/suite_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#1911 feat: reserved capacity support
  designs/capacity-reservations.md
  kwok/cloudprovider/cloudprovider.go
  kwok/cloudprovider/helpers.go
  kwok/tools/gen_instance_types.go
  pkg/apis/v1/labels.go
  pkg/cloudprovider/fake/cloudprovider.go
  pkg/cloudprovider/fake/instancetype.go
  pkg/cloudprovider/types.go
  pkg/controllers/disruption/consolidation.go
  pkg/controllers/disruption/consolidation_test.go
  pkg/controllers/disruption/drift_test.go
  pkg/controllers/disruption/helpers.go
  pkg/controllers/disruption/suite_test.go
  pkg/controllers/disruption/types.go
  pkg/controllers/nodeclaim/disruption/drift.go
  pkg/controllers/nodeclaim/disruption/suite_test.go
  pkg/controllers/provisioning/provisioner.go
  pkg/controllers/provisioning/scheduling/instance_selection_test.go
  pkg/controllers/provisioning/scheduling/nodeclaim.go
  pkg/controllers/provisioning/scheduling/nodeclaimtemplate.go
  pkg/controllers/provisioning/scheduling/reservationmanager.go
  pkg/controllers/provisioning/scheduling/scheduler.go
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
  pkg/controllers/provisioning/scheduling/suite_test.go
  pkg/controllers/provisioning/suite_test.go
  pkg/operator/options/options.go
  pkg/operator/options/suite_test.go
  pkg/test/options.go
  pkg/test/v1alpha1/labels.go
Labels: cncf-cla: yes, lgtm, approved, size/XXL

#2036 chore: Backport removal registration enforcement 1.2.x
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/events.go
  pkg/controllers/nodeclaim/lifecycle/initialization_test.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#2029 chore: backport removal of registration enforcement 1.0.x
  .golangci.yaml
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/events.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
  test/pkg/environment/common/monitor.go
Labels: cncf-cla: yes, lgtm, approved, size/M

#2031 chore: Backport removal registration enforcement 1.1.x
  go.mod
  kwok/apis/crds/karpenter.kwok.sh_kwoknodeclasses.yaml
  kwok/charts/crds/karpenter.sh_nodeclaims.yaml
  kwok/charts/crds/karpenter.sh_nodepools.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/controllers/nodeclaim/lifecycle/controller.go
  pkg/controllers/nodeclaim/lifecycle/events.go
  pkg/controllers/nodeclaim/lifecycle/initialization_test.go
  pkg/controllers/nodeclaim/lifecycle/registration.go
  pkg/controllers/nodeclaim/lifecycle/registration_test.go
  pkg/controllers/nodeclaim/lifecycle/suite_test.go
  pkg/controllers/nodeclaim/lifecycle/termination_test.go
  pkg/test/v1alpha1/crds/karpenter.test.sh_testnodeclasses.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L

#2041 test: Including test options into the scheduling benchmark context
  pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
